### ISSUE TITLE
Missing assets in mirador viewer

### ISSUE THREAD

**Issue by gravesm** [MITLibraries/tryiiif#14]
There are a bunch of assets missing from the mirador viewer. The most obvious are the web fonts used in UI elements of the viewer, resulting in unicode boxes.

**Comment by JPrevost** [comment]
Ah, probably from the great idea I had to pull out everything we didn't need in the initial PR.

**Comment by szendeh** [comment]
I missed my shot at auto-closing this because I forgot to include the special wording in my commit.

**Comment by gravesm** [comment]
This is still not fixed. In particular, I'm getting 404s for:
- http://tryiiif.herokuapp.com/static/vendor/fonts/fontawesome-webfont.woff?v=4.1.0
- http://tryiiif.herokuapp.com/static/vendor/fonts/fontawesome-webfont.woff?v=4.1.0

**Comment by JPrevost** [comment]
Works on staging so once we promote that it looks like this is indeed fixed.
http://tryiiif-staging.herokuapp.com/static/vendor/fonts/fontawesome-webfont.woff?v=4.1.0

**Comment by JPrevost** [comment]
Promoted staging to production and it seems fine so re-closing.

**Comment by gravesm** [comment]
Ah, right. I forgot it needed promoting. My bad.
