### ISSUE TITLE
Deal with errors during communication with IIIF server

### ISSUE THREAD

**Issue by gravesm** [MITLibraries/tryiiif#21]
When the form is submitted, if the IIIF server returns an error, the application just uses the default error page. We should probably either create a branded error page or send the user back to the form with some sort of flash message.

**Comment by richardrodgers** [comment]
I'd consider 2 dimensions to this: first, as the OP states, we need a better error page for the viewer. But second, I think we might consider validation _before_ the IIIF server call when we can deliver even more useful (targeted) information. Examples:
It's really easy to mistype or mis-paste an URL (you can truncate it, etc) into a form. Why not verify that the URL is OK before sending to the image server. It would be easy to detect:
(1) malformed URL
(2) URL that won't resolve (make HEAD call?) or is not accessible (permissions, etc)
(3) (maybe not so easy) - URL that isn't an image

Then the server could say something very specific/helpful like:

"This URL is not well-formed Can you check it?",  etc

**Comment by JPrevost** [comment]
The HEAD command might tell us both 2 and 3:

```
 $ curl --head https://dome.mit.edu/bitstream/handle/1721.3/176472/249875_cp.jpg?sequence=1
HTTP/1.1 200 OK
Date: Wed, 08 Jun 2016 17:17:27 GMT
Set-Cookie: JSESSIONID=4B25D60DF4DDD027D4B98758284C3F8E; Path=/; Secure
X-Cocoon-Version: 2.2.0
Vary: User-Agent
Last-Modified: Thu, 21 Jan 2016 07:21:09 GMT
Expires: Wed, 08 Jun 2016 18:17:27 GMT
Content-Type: image/jpeg
Content-Length: 1189699
Strict-Transport-Security: max-age=15768000
```

**Comment by gravesm** [comment]
I'm not sure I would trust content-type.

**Comment by gravesm** [comment]
I'll also add that I've seen cases where HEAD requests are not supported (yeah, I know). I would probably be pretty rare, but imagine the experience where we tell a user their link is wrong and they can see that it's working.

**Comment by richardrodgers** [comment]
Fair enough - but also imagine a slew of totally opaque/generic Server Error responses where there are easily discoverable causes. For the use-case (casual, anonymous, occasional users) - I would vote in favor of clarity over almost anything else

**Comment by JPrevost** [comment]
One option would be to implement by calling HEAD and if it fails or content/type doesn't look imagey, we could display "we aren't sure if that image will work... wanna try anyway?" dialog. And log stuff around this explicitly so we can see if it's working reasonably well or if it needs different logic.

**Comment by gravesm** [comment]
What if we made the HEAD request, then made the request for the info.json, and if that failed used the response from the HEAD request to generate a helpful error message?

**Comment by JPrevost** [comment]
I think in that case it maybe makes more sense to request info.json, and if that fails, request HEAD and use that for the error message.

**Comment by richardrodgers** [comment]
Sure - 'preflighting' to the image server seems reasonable also , or the combination approach mentioned by @mgraves. Either way, I'm just thinking we need to help the user somehow with information we can discover (however solid it is:  as noted, we can caveat our messages, or allow overrides)
