### ISSUE TITLE
Remove unnecessary files from vendored UV

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/tryiiif#24]

**Comment by matt-bernhardt** [comment]
The intent here is to keep things as small as possible, without running into problems like #14 - right?

I'm happy to trim our implementation of UV down as much as I can.

**Comment by JPrevost** [comment]
Yeah. It doesn't need all the development stuff, just what is required.

**Comment by matt-bernhardt** [comment]
Ok, I'll take this.
